add name
Danil1252/resume pull request #1
Opened 2022-05-19 19:06 UTC by kokojer

2022-05-19 19:17 UTC, kokojer commented
dada

2022-05-20 10:52 UTC, Danil1252 reviewed
Привет

2022-05-20 10:52 UTC, Danil1252 commented on index.html
> +							Hi, I am vinik,<br> Creative Technologist
Не нравится

2022-05-20 10:56 UTC, Danil1252 requested changes
Перед слиянием нужно проконсультироваться с  Danil1252

2022-05-20 10:59 UTC, merged